[package]
name = "rsa_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"
num-bigint = "0.4"
num-traits = "0.2"
modinverse = "0.1"
miller_rabin = "1.0"
sha2 = "0.10.9"
rug = "1.27.0"

